[ignore]
unit = [
	"tests/unit/modules/test_boto3_elasticsearch.py",
	"tests/unit/modules/test_boto3_route53.py",
	"tests/unit/modules/test_boto_route53.py",
	"tests/unit/utils/test_boto3mod.py",
]
integration = [
]
[skip]
unit = [
	"tests/pytests/unit/grains/test_core.py::test_get_server_id",
	"tests/pytests/unit/_logging/handlers/test_deferred_stream_handler.py::test_deferred_write_on_flush",
	"tests/pytests/unit/_logging/handlers/test_deferred_stream_handler.py::test_sync_with_handlers",
	"tests/pytests/unit/modules/file/test_file_module.py::test_check_file_meta_binary_contents",
	"tests/pytests/unit/modules/test_linux_shadow.py::test_gen_password[md5-passlib]",
	"tests/pytests/unit/modules/test_linux_shadow.py::test_gen_password[sha256-passlib]",
	"tests/pytests/unit/modules/test_linux_shadow.py::test_gen_password[sha512-passlib]",
	"tests/pytests/unit/modules/test_pip.py::test_fix4361",
	"tests/pytests/unit/modules/test_pip.py::test_install_build_argument_in_resulting_command",
	"tests/pytests/unit/modules/test_pip.py::test_install_cached_requirements_used",
	"tests/pytests/unit/modules/test_pip.py::test_install_download_argument_in_resulting_command",
	"tests/pytests/unit/modules/test_pip.py::test_install_download_cache_dir_arguments_in_resulting_command",
	"tests/pytests/unit/modules/test_pip.py::test_install_exists_action_argument_in_resulting_command",
	"tests/pytests/unit/modules/test_pip.py::test_install_extra_args_arguments_in_resulting_command",
	"tests/pytests/unit/modules/test_pip.py::test_install_extra_index_url_argument_in_resulting_command",
	"tests/pytests/unit/modules/test_pip.py::test_install_force_reinstall_argument_in_resulting_command",
	"tests/pytests/unit/modules/test_pip.py::test_install_frozen_app",
	"tests/pytests/unit/modules/test_pip.py::test_install_global_options_argument_in_resulting_command",
	"tests/pytests/unit/modules/test_pip.py::test_install_global_proxy_in_resulting_command",
	"tests/pytests/unit/modules/test_pip.py::test_install_ignore_installed_argument_in_resulting_command",
	"tests/pytests/unit/modules/test_pip.py::test_install_index_url_argument_in_resulting_command",
	"tests/pytests/unit/modules/test_pip.py::test_install_install_options_argument_in_resulting_command",
	"tests/pytests/unit/modules/test_pip.py::test_install_log_argument_in_resulting_command",
	"tests/pytests/unit/modules/test_pip.py::test_install_multiple_editable",
	"tests/pytests/unit/modules/test_pip.py::test_install_multiple_pkgs_and_editables",
	"tests/pytests/unit/modules/test_pip.py::test_install_multiple_requirements_arguments_in_resulting_command",
	"tests/pytests/unit/modules/test_pip.py::test_install_no_deps_argument_in_resulting_command",
	"tests/pytests/unit/modules/test_pip.py::test_install_no_download_argument_in_resulting_command",
	"tests/pytests/unit/modules/test_pip.py::test_install_no_index_argument_in_resulting_command",
	"tests/pytests/unit/modules/test_pip.py::test_install_no_install_argument_in_resulting_command",
	"tests/pytests/unit/modules/test_pip.py::test_install_pre_argument_in_resulting_command",
	"tests/pytests/unit/modules/test_pip.py::test_install_proxy_argument_in_resulting_command",
	"tests/pytests/unit/modules/test_pip.py::test_install_proxy_false_argument_in_resulting_command",
	"tests/pytests/unit/modules/test_pip.py::test_install_source_app",
	"tests/pytests/unit/modules/test_pip.py::test_install_source_argument_in_resulting_command",
	"tests/pytests/unit/modules/test_pip.py::test_install_timeout_argument_in_resulting_command",
	"tests/pytests/unit/modules/test_pip.py::test_install_upgrade_argument_in_resulting_command",
	"tests/pytests/unit/modules/test_pip.py::test_install_venv",
	"tests/pytests/unit/modules/test_pip.py::test_install_with_multiple_find_links",
	"tests/pytests/unit/modules/test_pip.py::test_issue5940_install_multiple_pip_mirrors",
	"tests/pytests/unit/modules/test_rpm_lowpkg.py::test_version_cmp_rpm_all_libraries[HAS_RPM]",
	"tests/pytests/unit/modules/test_transactional_update.py::test_call_fails_function",
	"tests/pytests/unit/modules/test_transactional_update.py::test_call_success_no_reboot",
	"tests/pytests/unit/modules/test_transactional_update.py::test_call_success_parameters",
	"tests/pytests/unit/modules/test_transactional_update.py::test_call_success_reboot",
	"tests/pytests/unit/states/file/test_tidied.py::test_tidied_age_size_args_AND_operator_age_not_size",
	"tests/pytests/unit/states/file/test_tidied.py::test_tidied_age_size_args_AND_operator_size_not_age",
	"tests/pytests/unit/states/test_pkgrepo.py::test_migrated_wrong_method",
	"tests/pytests/unit/utils/test_gitfs.py::test_full_id_pygit2",
	"tests/pytests/unit/utils/test_msgpack.py::test_load_encoding",
	"tests/pytests/unit/utils/test_pycrypto.py::test_gen_hash_crypt[blowfish-expected2]",
	"tests/pytests/unit/utils/test_pycrypto.py::test_gen_hash_crypt[crypt-expected4]",
	"tests/pytests/unit/utils/test_pycrypto.py::test_gen_hash_crypt[md5-expected3]",
	"tests/pytests/unit/utils/test_pycrypto.py::test_gen_hash_crypt[sha256-expected1]",
	"tests/pytests/unit/utils/test_pycrypto.py::test_gen_hash_crypt[sha512-expected0]",
	"tests/pytests/unit/utils/test_vt.py::test_log_sanitize[echo]",
	"tests/pytests/unit/utils/test_vt.py::test_log_sanitize[ls]",
	"tests/unit/cli/test_support.py::ProfileIntegrityTestCase::test_jobs_trace_template_profile",
	"tests/unit/cli/test_support.py::ProfileIntegrityTestCase::test_non_template_profiles_parseable",
	"tests/unit/cli/test_support.py::ProfileIntegrityTestCase::test_users_template_profile",
	"tests/unit/modules/test_dpkg_lowpkg.py::DpkgTestCase::test_info",
	"tests/unit/modules/test_zcbuildout.py::BuildoutOnlineTestCase::test_buildout",  # Unmaintained test - skipped upstream
	"tests/unit/modules/test_zcbuildout.py::BuildoutOnlineTestCase::test_run_buildout",  # Unmaintained test - skipped upstream
	"tests/unit/states/test_boto_apigateway.py::BotoApiGatewayTestCase::test_absent_when_failing_to_delete_a_deployment_no_longer_associated_with_any_stages",
	"tests/unit/states/test_boto_apigateway.py::BotoApiGatewayTestCase::test_absent_when_nuke_api_and_no_more_stages_deployments_remain",
	"tests/unit/states/test_boto_apigateway.py::BotoApiGatewayTestCase::test_absent_when_nuke_api_and_other_stages_deployments_exist",
	"tests/unit/states/test_boto_apigateway.py::BotoApiGatewayTestCase::test_absent_when_rest_api_does_not_exist",
	"tests/unit/states/test_boto_apigateway.py::BotoApiGatewayTestCase::test_absent_when_stage_is_invalid",
	"tests/unit/states/test_boto_apigateway.py::BotoApiGatewayTestCase::test_absent_when_stage_is_valid_and_only_one_stage_is_associated_to_deployment",
	"tests/unit/states/test_boto_apigateway.py::BotoApiGatewayTestCase::test_absent_when_stage_is_valid_and_two_stages_are_associated_to_deployment",
	"tests/unit/states/test_boto_apigateway.py::BotoApiGatewayTestCase::test_present_when_stage_associating_to_new_deployment_errored_on_api_creation",
	"tests/unit/states/test_boto_apigateway.py::BotoApiGatewayTestCase::test_present_when_stage_associating_to_new_deployment_errored_on_lambda_function_lookup",  # missing boto libraries
	"tests/unit/states/test_boto_apigateway.py::BotoApiGatewayTestCase::test_present_when_stage_associating_to_new_deployment_errored_on_model_creation",
	"tests/unit/states/test_boto_apigateway.py::BotoApiGatewayTestCase::test_present_when_stage_associating_to_new_deployment_errored_on_put_integration",  # missing boto libraries
	"tests/unit/states/test_boto_apigateway.py::BotoApiGatewayTestCase::test_present_when_stage_associating_to_new_deployment_errored_on_put_integration_response",  # missing boto libraries
	"tests/unit/states/test_boto_apigateway.py::BotoApiGatewayTestCase::test_present_when_stage_associating_to_new_deployment_errored_on_put_method",  # missing boto libraries
	"tests/unit/states/test_boto_apigateway.py::BotoApiGatewayTestCase::test_present_when_stage_associating_to_new_deployment_errored_on_put_method_response",  # missing boto libraries
	"tests/unit/states/test_boto_apigateway.py::BotoApiGatewayTestCase::test_present_when_stage_associating_to_new_deployment_errored_on_resource_creation",
	"tests/unit/states/test_boto_apigateway.py::BotoApiGatewayTestCase::test_present_when_stage_exists_and_is_to_associate_to_existing_deployment",
	"tests/unit/states/test_boto_apigateway.py::BotoApiGatewayTestCase::test_present_when_stage_is_already_at_desired_deployment",
	"tests/unit/states/test_boto_apigateway.py::BotoApiGatewayTestCase::test_present_when_stage_is_already_at_desired_deployment_and_needs_stage_variables_update",
	"tests/unit/states/test_boto_apigateway.py::BotoApiGatewayTestCase::test_present_when_stage_is_to_associate_to_new_deployment",  # missing boto libraries
	"tests/unit/states/test_boto_apigateway.py::BotoApiGatewayTestCase::test_present_when_swagger_file_is_invalid",
	"tests/unit/states/test_boto_cognitoidentity.py::BotoCognitoIdentityTestCase::test_absent_when_a_single_pool_exists",
	"tests/unit/states/test_boto_cognitoidentity.py::BotoCognitoIdentityTestCase::test_absent_when_erroring_on_delete_identity_pool",
	"tests/unit/states/test_boto_cognitoidentity.py::BotoCognitoIdentityTestCase::test_absent_when_failing_to_describe_identity_pools",
	"tests/unit/states/test_boto_cognitoidentity.py::BotoCognitoIdentityTestCase::test_absent_when_multiple_pool_exists_and_removeallmatched_flag_is_true",
	"tests/unit/states/test_boto_cognitoidentity.py::BotoCognitoIdentityTestCase::test_absent_when_pool_does_not_exist",
	"tests/unit/states/test_boto_cognitoidentity.py::BotoCognitoIdentityTestCase::test_absent_when_removeallmatched_is_false_and_multiple_pools_matched",
	"tests/unit/states/test_boto_cognitoidentity.py::BotoCognitoIdentityTestCase::test_present_when_failing_to_create_a_new_identity_pool",
	"tests/unit/states/test_boto_cognitoidentity.py::BotoCognitoIdentityTestCase::test_present_when_failing_to_describe_identity_pools",
	"tests/unit/states/test_boto_cognitoidentity.py::BotoCognitoIdentityTestCase::test_present_when_failing_to_get_identity_pool_roles",
	"tests/unit/states/test_boto_cognitoidentity.py::BotoCognitoIdentityTestCase::test_present_when_failing_to_set_identity_pool_roles",  # missing boto libraries
	"tests/unit/states/test_boto_cognitoidentity.py::BotoCognitoIdentityTestCase::test_present_when_failing_to_update_an_existing_identity_pool",
	"tests/unit/states/test_boto_cognitoidentity.py::BotoCognitoIdentityTestCase::test_present_when_multiple_pools_with_same_name_exist",
	"tests/unit/states/test_boto_cognitoidentity.py::BotoCognitoIdentityTestCase::test_present_when_pool_name_does_not_exist",  # missing boto libraries
	"tests/unit/states/test_boto_cognitoidentity.py::BotoCognitoIdentityTestCase::test_present_when_pool_name_exists",  # missing boto libraries
	"tests/unit/states/test_zcbuildout.py::BuildoutTestCase::test_installed",  # Unmaintained test - skipped upstream
	"tests/unit/test_config.py::APIConfigTestCase::test_api_config_log_file_values",
	"tests/unit/test_config.py::APIConfigTestCase::test_api_config_prepend_root_dirs_return",
	"tests/unit/test_config.py::ConfigTestCase::test_load_minion_config_from_environ_var",
	"tests/unit/test_config.py::SampleConfTest::test_conf_master_sample_is_commented",
	"tests/unit/transport/test_ipc.py::IPCMessagePubSubCase::test_async_reading_streamclosederror",
	"tests/unit/transport/test_ipc.py::IPCMessagePubSubCase::test_multi_client_reading",
	"tests/unit/utils/test_sdb.py::SdbTestCase::test_sqlite_get_found",
	"tests/unit/utils/test_templates.py::RenderTestCase::test_render_genshi_evaluate",
	"tests/unit/utils/test_templates.py::RenderTestCase::test_render_genshi_evaluate_condition",
	"tests/unit/utils/test_templates.py::RenderTestCase::test_render_genshi_sanity",
	"tests/unit/utils/test_templates.py::RenderTestCase::test_render_genshi_variable",
	"tests/unit/utils/test_templates.py::RenderTestCase::test_render_genshi_variable_replace",
	"tests/unit/utils/test_templates.py::RenderTestCase::test_render_mako_evaluate",
	"tests/unit/utils/test_templates.py::RenderTestCase::test_render_mako_evaluate_multi",
	"tests/unit/utils/test_templates.py::RenderTestCase::test_render_mako_sanity",
	"tests/unit/utils/test_templates.py::RenderTestCase::test_render_mako_variable",
]
integration = [
	"tests/integration/loader/test_ext_modules.py",  # Make pytest to stuck in sle15sp1 classic pkg
	"tests/integration/modules/test_cmdmod.py::CMDModuleTest::test_which_bin",
	"tests/integration/ssh/test_state.py::SSHStateTest::test_state_running",  # This test makes no sense with new locking mechanism for Salt SSH
	"tests/pytests/integration/master/test_clear_funcs.py::test_clearfuncs_config",
	"tests/pytests/integration/master/test_clear_funcs.py::test_fileroots_read",
	"tests/pytests/integration/master/test_clear_funcs.py::test_fileroots_write",
	"tests/pytests/integration/netapi/rest_tornado/test_minions_api_handler.py::test_get_no_mid",
	"tests/pytests/integration/netapi/rest_tornado/test_root_handler.py::test_simple_local_post",
	"tests/pytests/integration/netapi/rest_tornado/test_root_handler.py::test_simple_local_post_only_dictionary_request",
	"tests/pytests/integration/runners/state/orchestrate/test_events.py::test_jid_in_ret_event",
	"tests/pytests/integration/runners/state/orchestrate/test_events.py::test_orchestration_with_pillar_dot_items",
	"tests/pytests/integration/runners/state/orchestrate/test_events.py::test_parallel_orchestrations",
	"tests/pytests/integration/ssh/test_master.py::test_service",  # Failing when running on containers. dbus not available
]
functional = [
	"tests/pytests/functional/channel/test_server.py::test_pub_server_channel[transport(zeromq)]",
	"tests/pytests/functional/modules/test_sdb.py::test_setting_sdb_values_with_text_and_bytes_should_retain_data_types[bang]",
	"tests/pytests/functional/modules/test_sdb.py::test_setting_sdb_values_with_text_and_bytes_should_retain_data_types[expected_value2]",
	"tests/pytests/functional/modules/test_sdb.py::test_setting_sdb_values_with_text_and_bytes_should_retain_data_types[expected_value3]",
	"tests/pytests/functional/modules/test_x509_v2.py::test_create_certificate_from_privkey[ed25519]",
	"tests/pytests/functional/modules/test_x509_v2.py::test_create_certificate_from_privkey[ed448]",
	"tests/pytests/functional/modules/test_x509_v2.py::test_create_certificate_from_pubkey[ed25519]",
	"tests/pytests/functional/modules/test_x509_v2.py::test_create_certificate_from_pubkey[ed448]",
	"tests/pytests/functional/modules/test_x509_v2.py::test_create_certificate_self_signed[ed25519]",
	"tests/pytests/functional/modules/test_x509_v2.py::test_create_certificate_self_signed[ed448]",
	"tests/pytests/functional/modules/test_x509_v2.py::test_create_csr[ed25519]",
	"tests/pytests/functional/modules/test_x509_v2.py::test_create_csr[ed448]",
	"tests/pytests/functional/modules/test_x509_v2.py::test_get_private_key_size[ed25519-None]",
	"tests/pytests/functional/modules/test_x509_v2.py::test_get_private_key_size[ed448-None]",
	"tests/pytests/functional/modules/test_x509_v2.py::test_verify_signature[ed25519]",
	"tests/pytests/functional/modules/test_x509_v2.py::test_verify_signature[ed448]",
	"tests/pytests/functional/modules/test_yaml.py::test_lint_pre_render",
	"tests/pytests/functional/modules/test_yaml.py::test_lint_yaml",
	"tests/pytests/functional/modules/test_yaml.py::test_yamllint_virtual",
	"tests/pytests/functional/runners/test_winrepo.py::test_legacy_update_git_repos",
	"tests/pytests/functional/runners/test_winrepo.py::test_update_git_repos",
	"tests/pytests/functional/states/test_pip_state.py::test_pip_installed_name_test_mode",
	"tests/pytests/functional/states/test_pip_state.py::test_pip_installed_pkgs_test_mode",
	"tests/pytests/functional/transport/ipc/test_pub_server_channel.py::test_issue_36469_tcp",  # Make pytest to hang on sle15sp1
	"tests/pytests/functional/transport/ipc/test_pub_server_channel.py::test_publish_to_pubserv_ipc",  # Make pytest to hang during cleanup
	"tests/pytests/functional/transport/tcp/test_message_client.py::test_message_client_reconnect",
	"tests/pytests/functional/transport/zeromq/test_pub_server_channel.py::test_zeromq_filtering",  # Make pytest to hang on sle15sp1
	"tests/pytests/functional/utils/pyinstaller/rthooks/test_salt_utils_vt_terminal.py::test_vt_terminal_environ_cleanup[LD_LIBRARY_PATH]",
	"tests/pytests/functional/utils/pyinstaller/rthooks/test_salt_utils_vt_terminal.py::test_vt_terminal_environ_cleanup_original[LD_LIBRARY_PATH]",
	"tests/pytests/functional/utils/pyinstaller/rthooks/test_salt_utils_vt_terminal.py::test_vt_terminal_environ_cleanup_original_passed_directly[LD_LIBRARY_PATH]",
	"tests/pytests/functional/utils/pyinstaller/rthooks/test_salt_utils_vt_terminal.py::test_vt_terminal_environ_cleanup_passed_directly_not_removed[LD_LIBRARY_PATH]",
	"tests/pytests/functional/utils/pyinstaller/rthooks/test_subprocess.py::test_subprocess_popen_environ_cleanup[LD_LIBRARY_PATH]",
	"tests/pytests/functional/utils/pyinstaller/rthooks/test_subprocess.py::test_subprocess_popen_environ_cleanup_original[LD_LIBRARY_PATH]",
	"tests/pytests/functional/utils/pyinstaller/rthooks/test_subprocess.py::test_subprocess_popen_environ_cleanup_original_passed_directly[LD_LIBRARY_PATH]",
	"tests/pytests/functional/utils/pyinstaller/rthooks/test_subprocess.py::test_subprocess_popen_environ_cleanup_passed_directly_not_removed[LD_LIBRARY_PATH]",
	"tests/pytests/functional/utils/yamllint/test_yamllint.py::test_bad_yaml",
	"tests/pytests/functional/utils/yamllint/test_yamllint.py::test_config",
	"tests/pytests/functional/utils/yamllint/test_yamllint.py::test_good_yaml",
	"tests/pytests/functional/utils/yamllint/test_yamllint.py::test_has_yamllint",
	"tests/pytests/functional/utils/yamllint/test_yamllint.py::test_input_bytes",
	"tests/pytests/functional/utils/yamllint/test_yamllint.py::test_version",
]
scenarios = [
	"tests/pytests/scenarios/blackout/test_minion_blackout.py::test_blackout",
	"tests/pytests/scenarios/blackout/test_minion_blackout.py::test_blackout_nonwhitelist",
	"tests/pytests/scenarios/blackout/test_minion_blackout.py::test_blackout_whitelist",
	"tests/pytests/scenarios/multimaster/beacons/test_inotify.py::test_beacons_duplicate_53344",
	"tests/pytests/scenarios/reauth/test_reauth.py::test_reauth",
]
