[ignore]
unit = [
	"tests/unit/modules/test_boto3_elasticsearch.py",
	"tests/unit/modules/test_boto3_route53.py",
	"tests/unit/modules/test_boto_route53.py",
	"tests/unit/utils/test_boto3mod.py",
]
integration = [
]
[skip]
unit = [
	"tests/unit/modules/test_x509.py::X509TestCase::test_create_crl",  # Needs investigation: Fails only with Salt Bundle
	"tests/unit/modules/test_x509.py::X509TestCase::test_revoke_certificate_with_crl",  # Needs investigation: Fails only with Salt Bundle
	"tests/pytests/unit/grains/test_core.py::test_get_server_id",
#       Salt bundle currently doesn't package/ship passlib
	"tests/pytests/unit/modules/test_linux_shadow.py::test_gen_password[md5-passlib]",
	"tests/pytests/unit/modules/test_linux_shadow.py::test_gen_password[sha256-passlib]",
	"tests/pytests/unit/modules/test_linux_shadow.py::test_gen_password[sha512-passlib]",
	"tests/pytests/unit/modules/test_rpm_lowpkg.py::test_version_cmp_rpm_all_libraries[HAS_RPM]",
#       Requires Python 3.7. Non-bundle client uses Python 3.6, which doesn't have blowfish algorithm
	"tests/pytests/unit/utils/test_pycrypto.py::test_gen_hash_crypt[blowfish-expected2]",
	"tests/unit/cli/test_support.py::ProfileIntegrityTestCase::test_jobs_trace_template_profile",
	"tests/unit/cli/test_support.py::ProfileIntegrityTestCase::test_non_template_profiles_parseable",
	"tests/unit/cli/test_support.py::ProfileIntegrityTestCase::test_users_template_profile",
	"tests/unit/modules/test_dpkg_lowpkg.py::DpkgTestCase::test_info",
	# Upstream removed vendored Tornado in https://github.com/saltstack/salt/commit/4baea1a97be0389fabe5307d084579134a1f9b7a
	"tests/unit/transport/test_ipc.py::IPCMessagePubSubCase::test_multi_client_reading",
]
integration = [
	"tests/integration/cli/test_custom_module.py::SSHCustomModuleTest::test_ssh_custom_module",  # Needs investigation: Fails only with Salt Bundle
	"tests/integration/cli/test_custom_module.py::SSHCustomModuleTest::test_ssh_sls_with_custom_module",  # Needs investigation: Fails only with Salt Bundle
	"tests/integration/loader/test_ext_modules.py",  # Make pytest to stuck in sle15sp1 classic pkg
	"tests/integration/modules/test_pip.py::PipModuleTest::test_chained_requirements__non_absolute_file_path",  # Needs investigation: Fails only with Salt Bundle
	"tests/integration/modules/test_pip.py::PipModuleTest::test_issue_2087_missing_pip",  # Needs investigation: Fails only with Salt Bundle
	"tests/integration/modules/test_pip.py::PipModuleTest::test_issue_4805_nested_requirements",  # Needs investigation: Fails only with Salt Bundle
	"tests/integration/modules/test_pip.py::PipModuleTest::test_pip_install_multiple_editables_and_pkgs",  # Needs investigation: Fails only with Salt Bundle
	"tests/integration/modules/test_pip.py::PipModuleTest::test_requirements_as_list__non_absolute_file_path",  # Needs investigation: Fails only with Salt Bundle
	"tests/integration/modules/test_pip.py::PipModuleTest::test_requirements_as_list_of_chains__cwd_not_set__absolute_file_path",  # Needs investigation: Fails only with Salt Bundle
	"tests/integration/modules/test_pip.py::PipModuleTest::test_requirements_as_list_of_chains__cwd_set__absolute_file_path",  # Needs investigation: Fails only with Salt Bundle
	"tests/integration/modules/test_tls.py::TLSModuleTest::test_revoked_cert_should_return_False_from_validate",  # Needs investigation: Fails only with Salt Bundle
	"tests/integration/modules/test_tls.py::TLSModuleTest::test_validating_revoked_cert_with_no_crl_file_should_return_False",  # Needs investigation: Fails only with Salt Bundle
	"tests/integration/modules/test_tls.py::TLSModuleTest::test_with_existing_ca_signing_csr_should_produce_valid_cert",  # Needs investigation: Fails only with Salt Bundle
	"tests/integration/states/test_x509.py::x509Test::test_crl_managed",  # Needs investigation: Fails only with Salt Bundle - AttributeError: module 'lib' has no attribute 'X509_CRL_set1_lastUpdate'
	"tests/integration/states/test_x509.py::x509Test::test_crl_managed_replacing_existing_crl",  # Needs investigation: Fails only with Salt Bundle - AttributeError: module 'lib' has no attribute 'X509_CRL_set1_lastUpdate'
]
functional = [
	"tests/pytests/functional/channel/test_server.py::test_pub_server_channel[transport(zeromq)]",
	"tests/pytests/functional/modules/test_dockermod.py::test_docker_call",  # Needs investigation: Fails only with Salt Bundle - salt.exceptions.CommandExecutionError: /var/tmp/venv-salt-minion/bin/python.original: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.38' not found (required by /var/tmp/venv-salt-min...
	"tests/pytests/functional/modules/test_dockermod.py::test_docker_highstate",  # Needs investigation: Fails only with Salt Bundle - salt.exceptions.CommandExecutionError: /var/tmp/venv-salt-minion/bin/python.original: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.38' not found (required by /var/tmp/venv-salt-min...
	"tests/pytests/functional/modules/test_dockermod.py::test_docker_sls",  # Needs investigation: Fails only with Salt Bundle - salt.exceptions.CommandExecutionError: /var/tmp/venv-salt-minion/bin/python.original: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.38' not found (required by /var/tmp/venv-salt-min...
	"tests/pytests/functional/runners/test_winrepo.py::test_legacy_update_git_repos",
	"tests/pytests/functional/runners/test_winrepo.py::test_update_git_repos",
	"tests/pytests/functional/states/test_pip_state.py::test_pip_installed_name_test_mode",
	"tests/pytests/functional/states/test_pip_state.py::test_pip_installed_pkgs_test_mode",
	"tests/pytests/functional/states/test_x509_v2.py::test_private_key_managed_algo_change[existing_pk0]",  # Needs investigation: Fails only with Salt Bundle
	"tests/pytests/functional/states/test_x509_v2.py::test_private_key_managed_existing[existing_pk2]",  # Needs investigation: Fails only with Salt Bundle
	"tests/pytests/functional/states/test_x509_v2.py::test_private_key_managed_existing[existing_pk3]",  # Needs investigation: Fails only with Salt Bundle
	"tests/pytests/functional/states/test_x509_v2.py::test_private_key_managed[hunter1-der-ed25519]",  # Needs investigation: Fails only with Salt Bundle - AttributeError: module 'lib' has no attribute 'ERR_GET_LIB'
	"tests/pytests/functional/states/test_x509_v2.py::test_private_key_managed[hunter1-der-ed448]",  # Needs investigation: Fails only with Salt Bundle - AttributeError: module 'lib' has no attribute 'ERR_GET_LIB'
	"tests/pytests/functional/states/test_x509_v2.py::test_private_key_managed[hunter1-pem-ed25519]",  # Needs investigation: Fails only with Salt Bundle
	"tests/pytests/functional/states/test_x509_v2.py::test_private_key_managed[hunter1-pem-ed448]",  # Needs investigation: Fails only with Salt Bundle
	"tests/pytests/functional/states/test_x509_v2.py::test_private_key_managed[None-der-ed25519]",  # Needs investigation: Fails only with Salt Bundle
	"tests/pytests/functional/states/test_x509_v2.py::test_private_key_managed[None-der-ed448]",  # Needs investigation: Fails only with Salt Bundle
	"tests/pytests/functional/states/test_x509_v2.py::test_private_key_managed[None-pem-ed25519]",  # Needs investigation: Fails only with Salt Bundle
	"tests/pytests/functional/states/test_x509_v2.py::test_private_key_managed[None-pem-ed448]",  # Needs investigation: Fails only with Salt Bundle
	"tests/pytests/functional/transport/ipc/test_pub_server_channel.py::test_issue_36469_tcp",  # Make pytest to hang on sle15sp1
	"tests/pytests/functional/transport/ipc/test_pub_server_channel.py::test_publish_to_pubserv_ipc",  # Make pytest to hang during cleanup
	"tests/pytests/functional/transport/tcp/test_message_client.py::test_message_client_reconnect",
	"tests/pytests/functional/transport/zeromq/test_pub_server_channel.py::test_zeromq_filtering",  # Make pytest to hang on sle15sp1
        # We use python3-yamllint-1.22.1-150500.3.5.1.noarch, upstream hardcodes version 1.26.3 or greater
	"tests/pytests/functional/utils/yamllint/test_yamllint.py::test_version",
]
scenarios = [
	"tests/pytests/scenarios/blackout/test_minion_blackout.py::test_blackout",
	"tests/pytests/scenarios/blackout/test_minion_blackout.py::test_blackout_nonwhitelist",
	"tests/pytests/scenarios/blackout/test_minion_blackout.py::test_blackout_whitelist",
	"tests/pytests/scenarios/multimaster/beacons/test_inotify.py::test_beacons_duplicate_53344",
	"tests/pytests/scenarios/reauth/test_reauth.py::test_reauth",
]
